package br.com.zynger.influ;

import java.io.IOException;
import java.util.LinkedHashMap;

import android.app.Activity;
import android.app.Dialog;
import android.content.SharedPreferences;
import android.graphics.drawable.Drawable;
import android.os.AsyncTask;
import android.os.Bundle;
import android.preference.PreferenceManager;
import android.text.Html;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.Window;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import br.com.zynger.influ.model.Idol;
import br.com.zynger.influ.model.Theme;
import br.com.zynger.influ.util.FileHandler;
import br.com.zynger.influ.util.ImageManager;

public class IdolsActivity extends Activity {

	public final static String ARQUIVO = "idols";
	public final static int PRGER = 0;
	public final static int SGGER = 1;
	public final static int TCGER = 2;
	public final static int QTGER = 3;
	
	private SharedPreferences prefs;
	
	private ImageView iv_image;
	private TextView tv_name, tv_text;
	private LinearLayout ll_image;
	private static LinkedHashMap<String, Idol> idols;

	@SuppressWarnings("unchecked")
	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.idols);

		loadViews();
		updateTheme();
		
		prefs = PreferenceManager.getDefaultSharedPreferences(this);
		
		String appversion = SplashScreen.getAppVersion(this);
		String bd_version = FileHandler.openVersionData(this);
		if(appversion.equals(bd_version)) IdolsActivity.idols = (LinkedHashMap<String, Idol>) FileHandler.openBackup(this, ARQUIVO);
		else IdolsActivity.idols = null;
	}

	private void loadViews(){
		tv_name = (TextView) findViewById(R.idols.tv_name);
		ll_image = (LinearLayout) findViewById(R.idols.ll_image);
		iv_image = (ImageView) findViewById(R.idols.iv_image);
		tv_text = (TextView) findViewById(R.idols.tv_text);
		
		iv_image.setOnClickListener(new OnClickListener() {
			@Override
			public void onClick(View v) {
				Dialog d = new Dialog(v.getContext()); 
				d.requestWindowFeature(Window.FEATURE_NO_TITLE);
				d.setContentView(R.layout.history_stadium_images);
				ImageView iv = (ImageView) d.findViewById(R.history_stadium_images.iv);
				iv.setImageDrawable(iv_image.getDrawable());
				d.setCanceledOnTouchOutside(true);
				d.show();
			}
		});
	}
	
	private void updateTheme() {
		Theme t = (Theme) FileHandler.openBackup(this, ThemeChooserActivity.ARQUIVO);
		
		findViewById(R.idols.ll_actbg).setBackgroundColor(t.getAct_background());
		findViewById(R.idols.ll_actbg2).setBackgroundColor(t.getAct_background());
		findViewById(R.idols.ll_idolname).setBackgroundColor(t.getContent_background());
		findViewById(R.idols.ll_image).setBackgroundColor(t.getContent_background());
		findViewById(R.idols.ll_idoltext).setBackgroundColor(t.getContent_background());
		findViewById(R.idols.ll_actbg).invalidate();
	}

	@Override
	protected void onResume() {
		String name = this.getIntent().getStringExtra("IDOL_NAME");
		
		if(IdolsActivity.idols != null) setValues(name);
		else{
			IdolsActivity.idols = loadContent();
			FileHandler.saveBackup(this, ARQUIVO, IdolsActivity.idols);
			FileHandler.saveVersionData(this, SplashScreen.getAppVersion(this));
			setValues(name);
		}
		super.onResume();
	}

	public static LinkedHashMap<String, Idol> loadContent() {
		IdolsActivity.idols = new LinkedHashMap<String, Idol>();
		
		// 1902-1930 //
		createIdol(PRGER, "Fortes", "http://www.fluminense.com.br/site/futebol/wp-content/uploads/2011/06/fortes1.jpg", "Agostinho Fortes Filho foi o mais completo médio de seu tempo.<br /><br />Campeão Carioca em 1917, com apenas 16 anos de idade, 1918, 1919 e 1924, Campeão Sul-americano com a Seleção Brasileira em 1919 e 1922, e duas vezes Campeão Brasileiro de seleções.<br /><br />Disputou a Copa do Mundo de 1930, no Uruguai. Em campo, tinha dupla personalidade: atuava com fibra incomum, como se estivesse decidindo a final de um campeonato, mas, durante o jogo, não cessava de pilheriar com os companheiros, os adversários e o público, a despeito das advertências e censuras do severo capitão Chico Netto e de seus ex-professores Welfare, no Ginásio Anglo Brasileiro, e Oswaldo Gomes, no Colégio Alfredo Gomes, todos integrantes da equipe de amadores que conquistou o primeiro Tricampeonato da Cidade.<br /><br />Neco, o extraordinário meia-direita paulista, também Campeão Sul-Americano em 1919 e 1922, era grande amigo do craque tricolor, mas não gostava de enfrentá-lo porque, desabafava desalentado, “Fortes o irritava e o anulava com suas molecagens”.<br /><br />A torcida do Fluminense, então, divertia-se a valer com as diabruras de Fortes, e não raro, em vez de palmas ou gritos de incentivo, ressoava nas arquibancadas a gargalhada estrepitosa e comunicativa da massa.<br /><br />Certa vez, no estádio de São Januário, Fortes, ao ser driblado dentro da área, cometeu escandaloso pênalti no arisco centro-avante Russinho, segurando-o, abraçando-o e aplicando-lhe demorado beijo no rosto suado, enquanto a bola rolava mansamente para as mãos do arqueiro. O juiz, perplexo, nada marcou e a social do Vasco explodiu em risadas e comentários indulgentes: “O rapaz sabe jogar, mas gosta duma boa patuscada. É sempre melhor que machucar o adversário”. Era assim Agostinho Fortes Filho, o irrequieto Dadá, ídolo da torcida tricolor, que mais tarde trocou as chuteiras pela espingarda de caçador nas matas e alagadiços de Jacarepaguá.<br /><br />Participou de 230 jogos pelo Fluminense tendo marcado 16 gols.");
		createIdol(PRGER, "Horácio da Costa Santos", "http://www.fluminense.com.br/site/futebol/wp-content/uploads/2011/06/horaciocosta.jpg", "Grande atacante tricolor que atuou pelo Flu de 1902 a 1906 e posteriormente em 1908.<br /><br />Foi em sua residência, no dia 21 de julho de 1902, que nasceu a legenda chamada Fluminense Football Club.<br /><br />Como jogador, atacante, marcou 3 gols no primeiro jogo oficial da história do clube no amistoso contra o Rio Football Club, quando vencemos por 8×0.<br /><br />Foi ainda o primeiro artilheiro do Campeonato Carioca em 1906, tendo marcado 18 gols em 10 jogos, com a espetacular média de 1,8 gols por partida.<br /><br />Pelo tricolor foi Campeão Carioca em 1906 e 1908.<br /><br />Participou de 48 jogos, tendo marcado 34 gols.");
		createIdol(PRGER, "Marcos Carneiro de Mendonça", "http://www.fluminense.com.br/site/futebol/wp-content/uploads/2011/06/mendonca.jpg", "Esse mineiro de Cataguases deu início, em 1914, à tradição tricolor de formar grandes goleiros. A tranqüilidade, o sentido de colocação e apurado reflexo o consagraram na posição, tendo disputado 127 partidas pelo Fluminense e sagrando-se tricampeão carioca em 1917/18/19.<br /><br />Com todos esses atributos, o caminho natural seria a seleção brasileira, sendo seu primeiro goleiro e até hoje o mais jovem que já a defendeu (19 anos).<br /><br />Com 1,87m de altura e maneira elegante de se vestir e de se portar, era bastante admirando pelas moças da sociedade carioca da época. Daí reza a lenda de ter sido cunhada a expressão torcedor: as donzelas que assistiam às partidas torciam as luvas ou os lenços para aplacar a ansiedade.<br /><br />Após exitosa carreira futebolística, Marcos dedicou-se à profissão de historiador sem, contudo, abandonar suas atividades no Clube, sendo inclusive seu presidente na época do bicampeonato de 1940/1941.");
		createIdol(PRGER, "Oswaldo Gomes", "http://www.fluminense.com.br/site/futebol/wp-content/uploads/2011/06/gomes.jpg", "Recordista absoluto em conquistas de Campeonatos Cariocas com 8 títulos entre 1906 e 1919.<br /><br />Titular absoluto em 12 campeonatos disputados pelo Fluminense e um dos 2 titulares que se recusaram a abandonar o Fluminense para abrir o departamento de futebol do Flamengo.<br /><br />Exemplo de eficiência, dedicação e amor ao tricolor, foi eleito, em 1921, presidente da C.B.D, atual C.B.F.");
		createIdol(PRGER, "Preguinho", "http://www.fluminense.com.br/site/futebol/wp-content/uploads/2011/06/prego.jpg", "João Coelho Netto, o Preguinho, foi um atleta completo. Competiu em oito modalidades pelo Fluminense: futebol, vôlei, basquete, pólo aquático, saltos ornamentais, natação, hóquei e atletismo.<br /><br />Preguinho entrou para a galeria de grandes ídolos tricolores, sendo o autor do primeiro gol brasileiro em uma Copa do Mundo, em jogo contra a Iugoslávia, no Mundial de 1930, realizado no Uruguai.<br /><br />Os 55 títulos e as 387 medalhas nas oito modalidades que praticava o tornaram não só um ídolo, mas um herói tricolor, sendo por isso laureado com o primeiro título de grande benemérito atleta.<br /><br />Após sua morte, em 1979, o Prego – como era chamado pelos íntimos – seguiu merecidamente reverenciado, com um busto na sede do clube e a concessão de seu nome ao ginásio do Fluminense.");
		createIdol(PRGER, "Victor Etchegaray", "http://www.fluminense.com.br/site/futebol/wp-content/uploads/2011/06/victoetche.jpg", "Víctor François Etchegaray, nasceu em 07/04/1878.<br /><br />O zagueiro tricolor que sempre foi bastante elogiado pelo grande Marcos Carneiro de Mendonça.<br /><br />Foi um dos fundadores do clube, e marcava sua presença por sua elegância e toque refinado. Participou da primeira partida oficial do Fluminense e fez parte da equipe que conquistou o histórico Tetracampeonato Carioca de 1906/1907/1908 e 1909.<br /><br />Em 1912, voltou a jogar algumas partidas pelo tricolor.<br /><br />Participou de 77 jogos tendo marcado 1 gol.<br /><br />Faleceu em 13 de julho de 1915.");
		createIdol(PRGER, "Welfare", "http://www.fluminense.com.br/site/futebol/wp-content/uploads/2011/06/welfare.jpg", "Inglês de Liverpool, o habilidoso atacante foi o artilheiro do primeiro tricampeonato, com 56 gols.<br /><br />Jogou pelo clube de 1913 a 1924 e voltou ao Fluminense em 1952, apenas para participar da festa do cinquentenário do clube que seus gols ajudaram a tornar uma potência no futebol. Só assim se animaria a deixar a tranquila Angra dos Reis, onde fincara raízes depois de abandonar as coisas do esporte.<br /><br />Naquele julho, sempre cercado e reverenciado por vários ex-companheiros do épico tricampeonato 1917/18/19, o gigante ruivo-grisalho nem parecia ser – e continua sendo até hoje – o artilheiro com a maior média de gols no Fluminense: 163 gols em 166 jogos!");
		// 1931-1960 //
		createIdol(SGGER, "Ademir Menezes", "http://www.soumaisflu.com.br/media/wiki/128/1/4/0/6/b_20110305233308_ademir_menezes_ademir_menezes.jpg", "Campeão pernambucano pelo Sport Club Recife sendo o artilheiro do campeonato de 1941, o então jovem craque conhecido como “Queixada”, devido ao queixo proeminente, rapidamente tornou-se sonho de consumo dos grandes clubes do Rio de Janeiro, entre eles o Fluminense, que o perdeu, por uma diferença no pagamento das luvas, para o Vasco, onde acabou se consagrando. Ademir foi o primeiro jogador profissional a exigir o pagamento de luvas na assinatura de contrato.<br /><br />No início do ano de 1946 o Fluminense contratou o técnico Gentil Cardoso que, de pronto, proferiu a célebre frase: \"Dêem-me o Ademir que lhes darei o campeonato\". O Fluminense não mediu esforços e o arrebatou de São Januário para integrar seu elenco durante o Campeonato Carioca que viria a ser o mais disputado de todos pois, apesar do sistema de pontos corridos, quatro times acabaram empatados: Fluminense, América, Botafogo e Flamengo, obrigando a uma disputa extra, logo chamada pela imprensa de Supercampeonato.<br /><br />Em uma disputa recheada de craques, da linhagem de Zizinho, Danilo Alvim, Heleno de Freitas e Jorginho, entre outros, Ademir impôs seu estilo de jogo versátil, que o permitia jogar bem em qualquer posição do ataque e celebrizou-se pela arrancada fulminante em direção à meta adversária, com o queixo à frente, como que cortando o vento. Entrava na área em alta velocidade e, com um chute seco e rasteiro, executava a meta adversária, determinando o surgimento do ponta de lança.<br /><br />Foi dessa forma que no jogo final Ademir Menezes irrompeu pela área do Botafogo e fulminou a meta alvinegra, dando ao Fluminense o título de 1946 e cumprindo a profética frase de Gentil Cardoso.");
		createIdol(SGGER, "Batatais", "http://www.fluminense.com.br/site/futebol/wp-content/uploads/2011/06/batatais.jpg", "O Fluminense ficou famoso por uma tradição de possuir grandes goleiros. E se Marcos Carneiro de Mendonça foi o primeiro desta linhagem, o segundo foi com certeza Algisto Lorenzato, nascido em 20/05/1910 na cidade de Batatais no interior paulista. É considerado por muitos um dos melhores goleiros da história do futebol brasileiro.<br /><br />Batatais, como era conhecido, chegou ao clube em 1936, juntamente com alguns craques da seleção paulista. No mesmo ano, foi titular de todas as 18 partidas da vitoriosa campanha do Fluminense no Campeonato Carioca. Em 1937 e 1938, lá estava Batatais novamente, tornando-se o goleiro do segundo tricampeonato da história do Fluminense.<br /><br />Foi na temporada de 1938 que o goleiro chegou à Seleção Brasileira. Na Copa da França, no mesmo ano, Batatais jogou em duas das cinco partidas da equipe que terminou na terceira colocação.<br /><br />O arqueiro passava muita segurança à equipe. Era tão bom que, segundo contava o craque rubro- negro Zizinho, para superá-lo era preciso chutar errado para vencê-lo. Segundo o ex-jogador, Batatais estava sempre bem colocado e só “pegando mal na bola” era possível enganá-lo. O goleiro vestiu a camisa tricolor até 1945, conquistando ainda mais dois títulos cariocas, em 1940 e 1941, e participando do confuso Torneio Rio-São Paulo em que o Fluminense foi declarado campeão, junto com o Flamengo, em 1940.<br /><br />Na conquista do que ficou conhecido como o Fla x Flu da Lagoa, em 1941, foi considerado o grande nome do jogo, pois após uma contusão – foi pisoteado por Pirilo -, mesmo machucado garantiu o empate em 2 a 2, pois naquela época não eram previstas substituições.<br /><br />Pelo Flu atuou em 309 partidas, tendo sofrido 458 gols e ficado em 79 jogos sem sofrer nenhum.");
		createIdol(SGGER, "Bigode", "http://www.fluminense.com.br/site/futebol/wp-content/uploads/2011/06/bigode.jpg", "João Ferreira nasceu em Belo Horizonte-MG no dia 04/04/1922.<br /><br />Era um lateral esquerdo viril, que não tinha medo de cara feia e que se impunha aos atacantes com muita força física, embora fosse baixinho.<br /><br />Fez história defendendo o Atlético Mineiro, o Fluminense e o Flamengo, mas sua vida esportiva ficou marcada por um único lance: na Copa de 1950 ele marcava o ponta uruguaio Gighia, que fez o gol da vitória sobre o Brasil na final. Por isso, culparam-no, junto com Barbosa, pela grande decepção de ver o título mundial escapar em pleno Maracanã. Chegaram mesmo a dizer que Bigode se acovardara por ter sido agredido por Obdúlio Varela.<br /><br />É preciso que se faça justiça. Quem conhecia Bigode, como todos os seus companheiros de Seleção conheciam, sabe até hoje, os que ainda estão vivos – e há vários, que o mineiro Bigode não era homem de se acovardar, nem de ser agredido em pleno Maracanã sem “quebrar o pau”, fosse com quem fosse.<br /><br />Seja como for, Bigode passou pelo futebol brasileiro com glória e honra. Começou sua carreira jogando nas equipes amadoras do Industrial e do Combate, até se profissionalizar no Atlético Mineiro em 1940. Foi bicampeão mineiro em 1941/1942 e veio para o Fluminense em 1943, sagrando-se Campeão Carioca em 1946.<br /><br />Na Seleção Brasileira, Bigode foi vice-campeão mundial em 1950, como titular absoluto, e Campeão Sul-Americano em 1949. Ao todo fez 11 jogos pela Seleção, em 1949 e 1950. Depois não teve mais chance com o surgimento de Nilton Santos, que dominou a lateral esquerda durante anos e anos.<br /><br />Participou de 396 jogos pelo Fluminense, tendo atuado de 1945 a 1950 e de 1952 a 1955. Marcou 1 gol.");
		createIdol(SGGER, "Castilho", "http://www.fluminense.com.br/site/futebol/wp-content/uploads/2011/06/castilho1.jpg", "As qualidades técnicas do carioca Carlos Castilho eram incontestáveis, mas os adversários irados com as suas esplendorosas atuações atribuíam muito à sorte. Inveja, pois só o Fluminense tinha Castilho em sua equipe.<br /><br />Colocação, arrojo e segurança: foram esses atributos que o levaram a se tornar o maior ídolo da história do gol do Fluminense, tarefa nada fácil para quem vestiu a camisa de um clube que teve sua meta defendida, anteriormente, por Marcos Carneiro de Mendonça e Batatais.<br /><br />Além de sua excelência como jogador, Castilho, em plena era do profissionalismo, deu uma demonstração de amor ao Tricolor ao permitir a amputação de um dedo, constantemente lesionado, e desta forma voltar aos gramados com maior brevidade.<br /><br />Sorte? Não. Foram as qualidades técnicas e a paixão pelo Tricolor que o fizeram, além de ídolo um santo, o São Castilho.");
		createIdol(SGGER, "Didi", "http://www.fluminense.com.br/site/futebol/wp-content/uploads/2011/06/didi.jpg", "Natural de Campos, negro esguio, com pescoço à Modigliani, autor do primeiro gol do Maracanã, Waldir Pereira, certamente mudou a história do futebol mundial.<br /><br />Diferente dos grandes meias da época, que abasteciam seus respectivos ataques com passes em linha reta, à média e curta distâncias, Didi, com a invenção de uma balística indecifrável, conseguiu vincular o passe longo à essência do jogo.<br /><br />Jogador que tratava a bola com tal carinho e desvelo — a ela se referindo como \"a criança\" — encantou a todos, no mundial de 1958 (o primeiro ganho pelo Brasil), pela elegância de seu futebol, recebendo o prêmio de melhor jogador da Copa, passando a ser conhecido mundialmente como Mr. Football...<br /><br />Didi não via o jogo e sim antevia o jogo, e com essa característica transformou-se em um renomado treinador, que teve sob sua liderança jogadores como Rivelino, Paulo Cesar e Mario Sergio. Chamados por ele de \"meninos\", esses craques integraram a inesquecível máquina tricolor.<br /><br />\"Didi jogador de chute oblíquo e dissimulado como o olhar da Capitu\".");
		createIdol(SGGER, "Hércules", "http://www.fluminense.com.br/site/futebol/wp-content/uploads/2011/06/hercules.jpg", "Mineiro de Guaxupé, Hércules de Miranda era conhecido como “O Dinamitador”: tinha, segundo o cronista Geraldo Romualdo da Silva, do Jornal dos Sports, \"um canhão no pé esquerdo e um míssil no direito\".<br /><br />A torcida carioca o viu pela primeira vez no dia 7 de janeiro de 1934, em São Januário, onde cariocas e paulistas decidiram o título brasileiro e ele fez o gol da vitória paulista na prorrogação, depois do empate por 1 x 1 no tempo regulamentar.<br /><br />Hércules, que tinha passe livre depois que o São Paulo da Floresta se dissolvera, foi então contratado pelo Fluminense. Sua carreira começara na várzea paulista, e de 1930 a 1933 ele jogara no Juventus, de onde Paulo Machado de Carvalho o levou para o São Paulo. Houve a dissolução do clube e Hércules passou a atuar no Independente, time de exibição em São Paulo, ao lado de Friedenreich, Araken e Orozimbo.<br /><br />Para jogar no Flu, recebeu 10 contos de réis, uma fortuna na época, e passou a formar um grande elenco com Batatais, Ernesto Santos e Machado; Marcial, Brant e Orozimbo; Sobral, Russo, Gabardo e Vicentini. O apelido Dinamitador pegou a partir de 1936, quando o chute forte o consagrou definitivamente no Rio de Janeiro, graças a seus gols de falta. Em 1938, Hércules foi à Copa do Mundo, na França, mas o auge de sua carreira aconteceu no tricampeonato de 1936, 37 e 38, quando se tornou o artilheiro absoluto da campanha com 56 gols (23, em 1936; 23, em 1937; e 10, em 1938). Em 1940, foi de novo o artilheiro do time com 12 gols. Pelo clube fez 164 gols em 176 jogos.<br /><br />Em 1941, teve seu último ano de glória no Fluminense: surgiu Carneiro, que passou a dividir com ele a ponta-esquerda, e em 1943 Hércules, que encerrou a carreira cinco anos depois, pediu para ser vendido ao Corinthians – onde jogou ao lado de seu amigo Domingos da Guia, um dos zagueiros que mais trabalho tiveram para marcá-lo.");
		createIdol(SGGER, "Jair Marinho", "http://www.fluminense.com.br/site/futebol/wp-content/uploads/2011/06/jairmarinho.jpg", "Jair Marinho de Oliveira, nasceu no Rio de Janeiro-Niterói em 17/07/1936.<br /><br />Numa época em que os laterais apoiavam pouco o ataque, Jair Marinho se destacou como ótimo e implacável marcador.<br /><br />Nunca foi violento, pois também era um jogador habilidoso e de muita técnica.<br /><br />Começou no Fluminense, no qual foi Campeão Carioca em 1959, sendo convocado para a Copa do Mundo de 1962, no Chile. Não teve chance de jogar pois era reserva do grrande Djalma Santos.<br /><br />Foi também Campeão do Torneio Rio-São Paulo em 1960. Em 1964, transferiu-se para a Portuguesa e, no ano seguinte, para o Corinthians.<br /><br />Participou de 258 jogos pelo Flu, onde permaneceu de 1959 a 1963, tendo marcado 1 gol.");
		createIdol(SGGER, "Orlando Pingo de Ouro", "http://www.fluminense.com.br/site/futebol/wp-content/uploads/2011/06/orlando.jpg", "Esse pernambucano, ponta de lança hábil, veloz e excelente finalizador, não tinha porte físico privilegiado, o que era compensado com malícia, sutileza e inteligência, que o faziam livrar-se das mais inclementes defesas e, com isso, ganhar o apelido de \"Pingo de ouro\", dado pelo locutor Oduvaldo Cozzi.<br /><br />Orlando de Azevedo Viana estreou com a camisa do Fluminense no ano de 1943, permanecendo no clube até 1955, após participar de 311 jogos e marcar 188 gols.<br /><br />Ao encerrar a carreira Orlando não afastou-se de sua paixão, tornando-se frequentador diário do clube onde “batia” um tênis com os inúmeros amigos que fez durante a vida voltada para o esporte e, em especial, para o Fluminense.");
		createIdol(SGGER, "Pedro Amorim", "http://www.fluminense.com.br/site/futebol/wp-content/uploads/2011/06/amorim.gif", "Pedro Amorim Duarte, filho de um rico comerciante e fazendeiro de Senhor do Bonfim (BA), só queria saber de futebol.<br /><br />Nasceu em 13/10/1919 e faleceu em 25/09/1989 em sua terra natal.<br /><br />Dono da bola nas peladas da Praça Nova do Congresso, era o artilheiro mais aplaudido pelos adultos e dividia seus sonhos entre ser profissional de futebol e médico, por isso não mentia quando jurava a seu pai que se formaria em Medicina.<br /><br />Transferido para Salvador, logo ganhou vaga de titular na seleção de novos e aceitou convite para jogar no time amador do São Bento. E acabou indo treinar no Bahia, em que Gaia, lateral-esquerdo de gênio violento, retribuiu com um desleal pontapé no peito os dribles irreverentes levados entre as pernas.Pedro caiu desmaiado e seu irmão o proibiu de jogar futebol. Mas a paixão pela bola foi mais forte e um ano depois de estrear no Bahia ele era emprestado ao Botafogo, de Salvador, no qual jogou na ponta-direita, gostou da nova posição e despertou o interesse do Fluminense.<br /><br />O tricolor acabara de conquistar o tricampeonato de 1936, 1937 e 1938, e Pedro Amorim sentiu dificuldade para se adaptar a craques como Tim, Batatais, Romeu, Russo e Brant. Dava shows nos treinos, mas era um fracasso nos jogos.<br /><br />Num Fla-Flu, Romeu, com pena dele, passou-lhe a bola de calcanhar em vez de concluir – e Pedro Amorim chutou para fora. Foi xingado e vaiado.<br /><br />Até que certo dia, viajando para Niterói um velhinho desconhecido aproximou-se dele e disse:”Vi você jogar em Salvador. Esqueça o estádio cheio. Jogue seu futebol”. Na partida contra o Canto do Rio, em Caio Martins, Pedro Amorim seguiu o conselho do estranho, estraçalhou e se firmou como titular, até que uma entrada violenta de Rubens, do Madureira, o tirou do time em 1940. Mas em fins de 1941 ele retomou a camisa 7, então em poder de Adílson, e no ano seguinte chegou à Seleção Brasileira.<br /><br />Em 1946, Pedro Amorim não poderia ter exigido mais: foi Supercampeão pelo Flu, Campeão Brasileiro de seleções e ainda se formou em Medicina. Neste ano ele se vingou do zagueiro Norival, que gostava de Adílson e fizera severas críticas a Pedro Amorim, e por isso acabou sendo vendido ao Flamengo. No Fla-Flu de 1946, na Gávea, com o coração cheio de ódio, Pedro Amorim descontou: enfiou quantas bolas quis entre as pernas de Norival.<br /><br />Pedro Amorim formou em ataques famosos. Pela Seleção Carioca, ao lado de Zizinho, Heleno, Ademir e Vevé. Na Brasileira, com Romeu, Tim, Leônidas e Patesko. Até que em 1948, cumprindo a promessa feita ao pai Laurindo da Silva Duarte, voltou para Salvador para se dedicar somente à Medicina.<br /><br />Pelo Flu atuou em 210 jogos tendo marcado 78 gols.");
		createIdol(SGGER, "Píndaro", "http://www.fluminense.com.br/site/futebol/wp-content/uploads/2011/06/pindaro1.jpg", "Píndaro Possidonti Marconi nasceu em Santo Antônio de Pádua no dia 12/03/1925.<br /><br />Até o caso do jogador Leandro ( rubro-negro ), na Copa de 1986, Píndaro havia sido o único jogador da história do futebol brasileiro a pedir dispensa da Seleção Brasileira às vésperas de uma Copa do Mundo, em 1950.<br /><br />Lateral, muito técnico, era um marcador duro e persistente, com grande vigor físico. Junto com Castilho e Pinheiro, ficou gravado para sempre na memória dos tricolores.<br /><br />Até aqueles que não são Fluminense, mas viveram naquela época, sabem que todo o time do Fluminense começava com: “Castilho, Píndaro e Pinheiro…” . Jogadores que se tornaram símbolos pela dedicação e amor ao clube. Eram um verdadeiro paredão.<br /><br />Píndaro jogou no Fluminense de 1945 a 1956, conquistando o título Carioca de 1951 e o Mundial de Clubes de 1952.<br /><br />Participou de 257 jogos pelo Flu.");
		createIdol(SGGER, "Pinheiro", "http://www.fluminense.com.br/site/futebol/wp-content/uploads/2011/06/pinheiro.jpg", "Técnica razoável mas muita raça e boas cabeçadas fizeram de João Carlos Batista Pinheiro um dos grandes ídolos do Flu, no qual chegou em 1948 com 17 anos e fama de versátil adquirida no Americano – jogava bem como goleiro, centroavante, meia-armador e zagueiro.<br /><br />Nasceu em 13/01/1932 na cidade de Campos, Rio de Janeiro.<br /><br />Mas no tricolor ele se firmou como zagueiro-central, substituindo o argentino Lorenzo, e no mesmo ano foi campeão juvenil carioca, brasileiro e sul-americano. Chegou então o dia em que o técnico Oto Vieira o chamou: “Menino, vais entrar no time principal e marcar Heleno de Freitas”. As pernas grossas e fortes de Pinheiro tremeram diante do nome mitológico, mas em campo deu conta da missão – e Heleno saiu de campo inconformado com a audácia daquele jovem beque.<br /><br />Em 1951, quando Zezé Moreira levou o Fluminense a conquista do título impondo a marcação por zona, Pinheiro foi o grande líbero da defesa, além de respeitável cobrador de pênaltis: \"Eu escolhia um canto e mandava a bomba, quase sempre de bico para não dar tempo do goleiro se mexer\".<br /><br />Pinheiro não esquece a decisão contra o Bangu de Zizinho, Nívio, Moacir Bueno, Décio Esteves e Mirim. Este ameaçara distribuir pontapés em quem lhe atravessasse a frente. No primeiro jogo da melhor-de-três, Mirim quis agredir Telê, levou o troco e, depois que os dois foram expulsos, Pinheiro arrepiou em sua defesa, fazendo de Moacir Bueno sua vítima. Mas sempre contestou a fama de violento: \"Quem batia eram Píndaro e Bigode. Além disso, respeitava os adversários no Maracanã pois na casa dos outros vinha o troco\".<br /><br />Valente, Pinheiro se arrebentou no Fla-Flu de 1953, quando o rubro-negro arrancava para o tri de 1953, 1954, 1955: escanteio para o Fluminense e lá foi ele tentar o gol de empate. Deu azar: na disputa com o zagueiro Pavão, caiu e teve fratura da clavícula direita. Mas ele ganhou títulos memoráveis, como o Pan-Americano e a Taça Rio de 1952, o Torneio Rio-São Paulo (invicto) de 1957 e o de 1960, além do carioca de 1959.<br /><br />Ao encerrar a carreira como atleta, Pinheiro começou a de técnico sendo chamado em 1964 para reativar a divisão de infantis que o Fluminense havia abandonado em 1957. Treinando os profissionais em 1971, na decisão da Taça Guanabara, ao derrotar o Flamengo, deu novas provas de sua forte personalidade também fora de campo. O então vice-presidente João Boueri sugeriu uma escalação que não foi aceita por Pinheiro. O técnico colocou um time diferente em campo e, após a vitória por 3 a 1, avisou à equipe: \"Ganhamos o título, mas perdi meu emprego\". No dia seguinte, o ídolo tricolor assinou contrato com o Sport Recife.<br /><br />Participou de 605 jogos pelo clube, sendo o segundo jogador que mais vestiu a camisa tricolor. Marcou 51 gols.");
		createIdol(SGGER, "Romeu", "http://www.fluminense.com.br/site/futebol/wp-content/uploads/2011/06/romeu1.jpg", "Romeu Pellicciari foi, talvez, o jogador que transformou o meio campo no lugar aonde se pensa o jogo.<br /><br />Com toques sutis, que sempre buscavam os lados do campo, também costumava chegar à entrada da área para arremates de precisão cirúrgica; não sem antes jogar por terra os zagueiros adversários ao executar o famoso drible \"passo de ganso\", hoje conhecido como pedalada.");
		createIdol(SGGER, "Russo", "http://flupedia.wp-content/uploads.wordpress.com/2009/04/russo.jpg", "Russo é um dos grandes artilheiros da história do Fluminense Football Club, tendo feito 154 gols em 249 jogos, entre 1933 e 1944, sendo um dos destaques do famoso \"Fla-Flu da Lagoa\", na final do Campeonato Carioca de 1941, e tendo conquistado cinco campeonatos cariocas pelo tricolor.<br /><br />Sofreu uma grave contusão em 1938, tendo ido para Paris, a fim de se recuperar e onde chegou a jogar por um pequeno clube, o Cerele, retornando para o Fluminense em 1940, a tempo de se sagrar campeão carioca, e conseguindo recuperar a antiga forma.<br /><br />No Campeonato Carioca de 1941, fez parte do ataque que fez 106 gols, um feito jamais igualado neste torneio, tendo como compaheiros o argentino Rongo, Romeu Pellicciari, Tim e Hércules.<br /><br />Contava Tim que, no dia do Clássico Vovô de 4 de Setembro de 1943, no Estádio das Laranjeiras, o então técnico do Fluminense, o uruguaio Ondino Viera, no momento da distribuição de camisas e tarefas aos jogadores, pediu a Russo que marcasse o jogador Santamaría, um argentino que jogava no Botafogo, o que Russo recusou, devolvendo a camisa ao técnico. Interpelado por Ondino Viera, Russo explicou que sua posição em campo e suas características não lhe permitiriam executar bem a função, recomendando que o treinador escalasse Carlos Brant, que era volante e ainda sabia atacar. Vencido pelo argumento de Russo, Ondino preferiu deixá-lo entrar em campo e jogar como acreditava que seria o melhor para ele e para o tricolor. Resultado: o Fluminense ganhou do Botafogo por 5 a 3 e Russo marcou três gols");
		createIdol(SGGER, "Tim", "http://www.fluminense.com.br/site/futebol/wp-content/uploads/2011/06/tim.jpg", "Elba de Pádua Lima, paulista de Ribeirão Preto, chegou ao Fluminense para integrar um elenco que liderou o futebol carioca entre os anos de 1936 e 1943, sendo, nesse período, um dos destaques de uma equipe ganhadora de 5 títulos cariocas: um tricampeonato (1936/37/38) e um bicampeonato (1940/41).<br /><br />Famoso por sua habilidade na arte do drible, que desestabilizava os nervos e as estruturas das defesas adversárias, teve seu talento reconhecido e admirado por nossos rivais, os argentinos, que o apelidaram de \"El Peón\".<br /><br />Após encerrar a carreira nos gramados, Tim tornou-se técnico. Excelente estrategista, levou o time do Fluminense à conquista do Campeonato Carioca de 1964, numa emocionante “melhor de três” contra o Bangu.");
		createIdol(SGGER, "Telê", "http://www.fluminense.com.br/site/futebol/wp-content/uploads/2011/06/Telesantana1.jpg", "Este mineiro de Itabirito veio jogar no Fluminense, não por um projeto de vida, mas para a realização de um sonho, Telê Santana da Silva era tricolor desde sempre.<br /><br />Chegou para integrar a equipe de juvenis, base da seleção brasileira da categoria, onde seu futebol inteligente e objetivo logo despertou a atenção dos responsáveis pela equipe principal, da qual começou a fazer parte em 1951, com uma nova postura de jogo.<br /><br />O técnico Zezé Moreira viu no jogador de toques rápidos e grande mobilidade, Telê era incansável, a capacidade de compor o meio campo defensivo e chegar ao ataque para tabelar e concluir. Foi artilheiro no juvenil e o primeiro ponta que voltava para marcar.<br /><br />No ano de sua estréia no time principal, o destino reservou a Telê a façanha de ser o herói do título pois, atuando novamente como centroavante, foi autor dos dois gols que deram a vitória ao Fluminense no segundo jogo de uma acirrada disputa em melhor de três contra o Bangu.<br /><br />Mas não foram os gols que tornaram Telê um dos maiores ídolos do Fluminense, o que mais o identificava com a torcida pó de arroz era a dedicação, a movimentação constante a cada jogada, além de lucidez que deixava transpirar suor e seu amor ao tricolor. Mesmo nos momentos mais difíceis o torcedor sempre esperava algo do jogador de corpo franzino, que por isso foi chamado pela voz das arquibancadas de “Fio de Esperança”, em um concurso sugerido pelo dirigente tricolor Benício Ferreira Filho e promovido pelo Jornal dos Sports.<br /><br />Mas a vida de Telê não estaria ligada ao seu Fluminense só como jogador, pois aqui também começou vitoriosa carreira de técnico do juvenil, sendo campeão em 1968, No ano seguinte foi promovido a técnico do time principal, sendo campeão carioca numa final histórica contra o Flamengo e formando a base do time campeão do Torneio Gomes Pedrosa de 1970. Telê foi à vida, colecionou títulos, vitórias e se consagrou definitivamente em 1982, ao comandar a Seleção Brasileira que não ganhou a Copa o Mundo mas encantou o planeta com um futebol de altíssimo nível técnico.<br /><br />Onde estivesse, fosse em um clube ou na seleção, Telê deixava bem claro que ali estava por razões profissionais, mas que sua paixão era e sempre seria o Fluminense. O que fica patente é que a relação de Telê com o Tricolor transcende ao aspecto profissional e esportivo: trata-se de uma verdadeira história de amor.");
		createIdol(SGGER, "Waldo", "http://www.fluminense.com.br/site/futebol/wp-content/uploads/2011/06/waldo.jpg", "Waldo Machado da Silva, natural de Niterói, tornou-se sinônimo de gol para a torcida tricolor.<br /><br />Fazia gols de canela, com chutões desprovidos de dribles ou firulas. Sua genialidade residia justamente na capacidade de não perdê-los.<br /><br />Sua média no clube foi quase de um gol por partida. É o maior artilheiro do Fluminense, com 314 gols em 403 jogos.<br /><br />Atuou pelo clube de 1954 a 1961.");
		// 1961-1990 //
		createIdol(TCGER, "Amoroso", "http://www.fluminense.com.br/site/futebol/wp-content/uploads/2011/06/amoroso.jpg", "José Amoroso Filho, nasceu no Rio de Janeiro em 19 de setembro de 1937.<br /><br />Atacante, revelou-se nos juvenis do Botafogo, chegando a equipe principal. Foi adquirido pelo Fluminense por 10 milhões de cruzeiros, muito bem empregados. Dono de um oportunismo de dar inveja a muitos atacantes, chegou ao clube em 1964 e já neste ano tornou-se artilheiro do Campeonato Carioca com 19 gols e ídolo da torcida tricolor.<br /><br />Em jogo memorável, nas finais de 1964, o Fluminense enfrentou o Bangu em melhor de três partidas. Com Tim de técnico, no primeiro encontro vencemos por 1 x 0, gol de Amoroso e no segundopor 3 x 1.<br /><br />Amoroso considerado como ultrapassado pelo alvinegro, apesar de seus 26 anos, foi durante o campeonato um dos destaques da equipe do Fluminense.<br /><br />Permaneceu no clube de 1964 a 1968 tendo participado de 135 jogos e marcado 72 gols.<br /><br />O grande centroavante deu ao Fluminense muitas alegrias e por esse motivo figura em nossa seleta galeria de ídolos.");
		createIdol(TCGER, "Assis", "http://www.fluminense.com.br/site/futebol/wp-content/uploads/2011/06/assis.jpg", "Benedito de Assis da Silva, paulista, jogou no Fluminense de 1983 a 1987.<br /><br />Conhecido como Carrasco, Assis formou com Washington o Casal 20. A dupla famosa no futebol do Rio de Janeiro levou o clube ao título do Campeonato Estadual de 1983.<br /><br />No ano seguinte, ao lado de outros craques, comandou o Fluminense na conquista de mais um Estadual e do Brasileiro de 1984. A série de conquistas culminou com o tricampeonato em 85.<br /><br />Bastava tocar na bola para que Assis revelasse sua técnica apurada, futebol simples, de drible fácil e seu incrível dom para o jogo aéreo.<br /><br />Durante muitos anos uma canção ecoaria no Maracanã lotado em dias de Fla-Flu: \"Recordar é viver, Assis acabou com você\".");
		createIdol(TCGER, "Branco", "http://www.fluminense.com.br/site/futebol/wp-content/uploads/2011/06/branco.jpg", "Cláudio Ibraim Vaz Leal, gaúcho de Bagé, chegou ao Fluminense com 19 anos. Formou com o ponta-esquerda Tato uma das mais entrosadas duplas da história do clube.<br /><br />Extremamente técnico, vigoroso e com muita personalidade, tinha como sua maior arma o chute forte e com efeito nas cobranças de falta a longa distância.<br /><br />Trouxe para o clube o tricampeonato estadual de 83/84/85 e o Campeonato Brasileiro de 84. Em 1986 deixou o Fluminense para atuar na Europa.<br /><br />Em 1994, após disputar duas Copas do Mundo vestindo a camisa da Seleção Brasileira (1986/90), voltou às Laranjeiras e foi disputar sua terceira Copa, nos Estados Unidos, para fazer história ao cobrar espetacularmente uma falta na semifinal, contra a Holanda, e dar a vitória ao Brasil por 3 a 2.<br /><br />Após a conquista do tetracampeonato Mundial mais uma vez deixou o Tricolor, para voltar em 1998, e encerrar a carreira no Fluminense.");
		createIdol(TCGER, "Carlos Alberto Torres", "http://www.fluminense.com.br/site/futebol/wp-content/uploads/2011/06/catorres.jpg", "A trajetória do capitão do tricampeonato mundial do Brasil, no México, em 1970, começou no Fluminense.<br /><br />Um dos maiores jogadores da lateral-direita em todo o mundo Carlos Alberto Torres foi revelado pelo Tricolor, onde começou a jogar em 1960 e conquistou o primeiro título em 1964.<br /><br />Depois de quatro anos Carlos Alberto deixou o Flu e voltou em 1975, para integrar a Máquina Tricolor e levantar o bicampenato estadual em 75/76.<br /><br />De personalidade forte, um comandante dentro do campo, o \"Capita\", como passou a ser chamado depois do Mundial de 70, não se contentava em guardar a lateral e compor a linha de defesa. Suas subidas ao ataque não raramente resultavam em gols, como aquele que fechou a goleada em cima da Itália na final no México.<br /><br />O Fluminense foi o primeiro e o último clube pelo qual Carlos Alberto Torres jogou no Brasil.");
		createIdol(TCGER, "Delei", "http://www.fluminense.com.br/site/futebol/wp-content/uploads/2011/06/deleido.jpg", "Natural de Volta Redonda, Vanderlei Alves de Oliveira começou nas categorias de base do Fluminense e foi promovido a titular em 1980. Neste mesmo ano o meia ajudou a equipe a conquistar o título carioca sobre o Vasco.<br /><br />Foi ainda o principal armador de jogadas do meio campo tricolor na conquista do tricampeonato carioca de 1983/84/85, além de maestro do time campeão brasileiro de 84.<br /><br />Além da classe inconteste, Delei destacava-se pelo espírito de equipe, que o fazia jogar sempre para o time. Saiam de seus pés os melhores passes para os atacantes e pontas tricolores.<br /><br />Em 1983, por exemplo, na decisão do Campeonato Carioca contra o Flamengo, foi dele o magistral, irretocável lançamento que encontrou Assis livre na área para balançar as redes e garantir o título tricolor.<br /><br />O craque tem ainda na bagagem três títulos internacionais: Torneio de Seul (1984), Torneio de Paris (1987) e Copa Kirim (1987).");
		createIdol(TCGER, "Denílson", "http://www.fluminense.com.br/site/futebol/wp-content/uploads/2011/06/denilson.jpg", "O invejável porte físico – forte e alto – poderia ter levado Denílson Custódio Machado a sonhar com a posição de centroavante.<br />Seu futebol, no entanto, tinha características bem mais defensivas e a capacidade de desarmar o adversário fez com que Denílson se tornasse o primeiro verdadeiro cabeça-de-área do futebol brasileiro.<br /><br />Ainda jovem bateu na porta do Fluminense e, decidido, foi pedir uma oportunidade diretamente ao técnico Zezé Moreira. O treinador gostou de sua impetuosidade e o deixou treinar entre os juvenis, onde ficou até 1964, quando Tim o lançou no time profissional, que acabou conquistando naquele mesmo ano o título carioca.<br /><br />Ganhou de Nélson Rodrigues o apelido de “Rei Zulu” e na proteção da área tricolor colecionou ainda os Campeonatos Estaduais de 1969/71/73 e a Taça de Prata, em 70.<br />O bom futebol o levou à seleção brasileira e à disputa da Copa do Mundo de 66.<br />Ao todo defendeu o Brasil em 9 partidas internacionais e marcou dois gols.");
		createIdol(TCGER, "Doval", "http://www.fluminense.com.br/site/futebol/wp-content/uploads/2011/06/doval.jpg", "Nascido em Buenos Aires no dia 4 de janeiro de 1944, o Argentino Narciso Horácio Doval surgiu nas categorias de base do San Lorenzo, onde chegou a atuar como goleiro, posição a qual não se adaptou, pois após efetuar a defesa, partia para cima dos outros jogadores, driblando-os em direção a meta adversária. Devido a sua habilidade com a bola nos pés passou a atuar no meio de campo, até finalmente chegar à posição que o consagrou, como atacante.<br /><br />Doval atuou pela primeira vez no time titular do San Lorenzo com 16 anos, e já no início de sua carreira se destacou o suficiente para chamar a atenção dos dirigentes do Flamengo, e em 1969 chegou ao clube Rubro-Negro, onde atuou no ataque ao lado e de Zico.<br /><br />Em 1971, Doval retornou ao seu País natal para jogar futebol, foi para o Huracan onde atuou por uma temporada sem maiores destaques. Voltou em 1972 para o Flamengo, onde foi artilheiro do Campeonato Carioca de 1972 e campeão em 1972 e 1974.<br /><br />Amplamente identificado com o Flamengo e ídolo do Rubro-Negro, em 1976 Doval aceitou a proposta do presidente Tricolor Francisco Horta, e em uma troca de jogadores entre Flamengo e Fluminense, Doval veio para as Laranjeiras, deixando inconformada a torcida Rubro-Negra.<br /><br />Chegou ao Fluminense e logo ganhou a torcida Tricolor, com raça e vontade aliada a uma técnica impressionante, seu futebol é até hoje lembrado pela torcida.<br /><br />Doval entrou para a Máquina Tricolor que contava com, entre outros craques, Rivellino, Paulo César Cajú e Carlos Alberto Torres, entrando para a formação de uma das maiores equipes já montadas no mundo para a prática do futebol.<br /><br />Foi o artilheiro do campeonato Carioca de 1976 com 20 gols, onde também foi campeão pelo Fluminense, marcando o gol da final contra o Vasco, de cabeça, já na prorrogação, levando o título para as Laranjeiras.<br /><br />Atuou pelo Fluminense até 1978, jogando 141 partidas e marcando 71 gols. Deixou o Fluminense para retornar à Argentina e encerrar sua carreira em 1980 no clube que o revelou, o San Lorenzo.<br /><br />Faleceu aos 47 anos no dia 12 de Outubro de 1991, vítima de uma parada cardíaca, mas deixou marcado seu nome na história do futebol e do Fluminense Football Club.");
		createIdol(TCGER, "Edinho", "http://www.fluminense.com.br/site/futebol/wp-content/uploads/2011/06/edinho1.jpg", "A disposição eterna de vencer, a força física, a muralha que erguia na área, a impulsão que lhe garantia ganhar todas as bolas na cabeça, as avançadas velozes ao ataque e as cobranças de falta fizeram com que Édno Nazareth Filho escrevesse eu nome na história do Fluminense, onde começou a jogar futebol ainda menino, aos 13 anos. Aos 18 anos o jovem talento já estava entre os profissionais e foi um dos integrantes da Máquina Tricolor em 75/76.<br /><br />Em 1980 conquistou mais um título carioca, sobre o Vasco, com um detalhe: foi ele o autor do gol, ao converter uma falta.<br /><br />O futebol de Edinho fez com que disputasse três Copas do Mundo (1978/82 e 86).<br /><br />O zagueiro disputou 358 jogos, marcou 34 gols e voltou ao Fluminense como treinador, vencendo a Taça Guanabara em 1991 e 93.");
		createIdol(TCGER, "Félix", "http://www.fluminense.com.br/site/futebol/wp-content/uploads/2011/06/felix.jpg", "Por 10 anos Félix Mielli Venerando guardou o gol tricolor.<br /><br />Corria o ano de 1967 quando deixou a Portuguesa de Desportos e chegou às Laranjeiras para já entrar em campo no dia seguinte e garantir um empate com o Botafogo em 0 x 0.<br /><br />O camisa 1 só deixou a posição para encerrar a carreira, em 1973, depois de colecionar uma série de títulos, como a Taça de Prata, em 1970, e cinco Campeonatos Estaduais (1969/71/73/75 e 76).<br /><br />As boas atuações pelo Fluminense o levaram à seleção brasileira. Convocado por João Saldanha e mantido por Zagalo \"Gato Félix\", como ficou conhecido, conquistou o tricampeonato mundial no México em 1970 e calou alguns críticos que colocavam em dúvida seu futebol.");
		createIdol(TCGER, "Flávio Minuano", "http://www.fluminense.com.br/site/futebol/wp-content/uploads/2011/06/flavio.jpg", "O centroavante que deu ao Fluminense logo no seu primeiro ano de clube o título de campeão carioca em 1969, marcando o último gol da vitória tricolor por 3 x 2, sobre o Flamengo, foi um daqueles jogadores que parecem ter nascido com uma única finalidade: guardar a bola no fundo da rede adversária.<br /><br />Excelente cabeceador, Flávio Almeida da Fonseca chutava com as duas pernas, usava muito bem o corpo e, se era contido na movimentação, apresentava um incrível índice de aproveitamento de bolas na área convertidas em gol.<br /><br />Em 1970 o artilheiro do Campeonato Estadual de 1969, com 15 gols, era o homem-gol do Fluminense na conquista da Taça de Prata, assim como no bicampeonato carioca de 71. No ano seguinte Flávio deixou as Laranjeiras com um total de 92 gols marcados em 115 partidas.<br /><br />Um daqueles jogadores que deixaram saudades na memória tricolor.");
		createIdol(TCGER, "Gérson", "http://www.fluminense.com.br/site/futebol/wp-content/uploads/2011/06/gerson1.jpg", "O Canhotinha de Ouro armador na linha direta de Didi, de quem herdou os dons de organizar o jogo e a arte do passe.<br /><br />Com ele em campo o time ganhava um estrategista dentro das quatro linhas, pois rapidamente lia o jogo e orientava a colocação dos companheiros, sempre gesticulando e falando muito, ganhando com isso o apelido de \"Papagaio\", dados pelos companheiros de time e da seleção.<br /><br />Gerson de Oliveira Nunes detinha uma liderança natural, mesmo que não ostentasse a faixa de capitão.<br /><br />Jogador vitorioso, encerrou a carreira em 1973 vestindo a camisa do Fluminense, o seu clube de coração, tendo sido, inclusive, campeão carioca.");
		createIdol(TCGER, "Gil", "http://www.fluminense.com.br/site/futebol/wp-content/uploads/2011/06/gil.jpg", "Durante os quatro anos em que jogou pelo Fluminense – time que o elevou à condição de ídolo – o ponta-direita Gilberto Alves, o Gil, deu muitos títulos e inúmeras alegrias à torcida tricolor.Nasceu em 24 de dezembro de 1950, em Belo Horizonte.<br /><br />Começou nos infantis do Cruzeiro, profissionalizando-se em 1970 e vendeu seu passe, por 35 mil cruzeiros ao Vila Nova de Goiás. Foi emprestado ao Comercial de Mato Grosso onde tornou-se artilheiro do time no Campeonato Brasileiro, jogando como ponta-de-lança.<br /><br />O Flu trouxe Gil para as Laranjeiras em março de 1974 e o técnico Duque o colocou como centroavante, tentativa que não obteve êxito. Paulo Emílio então o escalou em sua antiga posição, a ponta direita.<br /><br />Com os lançamentos de Rivellino e suas investidas na diagonal, partindo da direita para o centro, apareceu no cenário nacional como matador e artilheiro. Seu grande porte físico lhe rendeu o apelido de “Búfalo”.<br /><br />Gil recorda os bons tempos em que jogou na Máquina Tricolor, o grande elenco do Fluminense Bicampeão Carioca de 1975/1976.<br /><br />Pelo Flu venceu os campeonatos cariocas de 1975 e 1976 e vários torneios internacionais conquistados pela chamada “máquina”.<br /><br />Suas atuações o levaram a seleção brasileira sendo importante destaque no Torneio Independência disputado nos EUA, onde o Brasil sagrou-se Campeão.<br /><br />Atuou no Fluminense junto com grande craques. Nossa escalação era: Renato, Carlos Alberto Torres, Miguel, Edinho e Rodrigues Neto; Carlos Alberto Pintinho, Rivellino e Dirceu; Gil, Doval e Paulo César Caju.<br /><br />Em 172 jogos pelo clube, marcou 75 gols.");
		createIdol(TCGER, "Lula", "http://www.fluminense.com.br/site/futebol/wp-content/uploads/2011/06/lula.jpg", "Não há um só tricolor que não abra um sorriso ao relembrar de Lula e sua velocidade pela ponta-esquerda do Fluminense no time que levantou os títulos do Campeonato Estadual de 1969/71/73, além da Taça de Prata, em 70.<br /><br />Mas o sorriso dos torcedores reflete, principalmente, a imagem do pernambucano Luís Ribeiro Pinto Neto empurrando para dentro do gol a bola que sobrou aos seus pés, após a dividida de Marco Antônio com o goleiro Ubirajara, aos 43 minutos do segundo tempo da final do Carioca de 1971, contra o Botafogo.<br /><br />Lula se transferiu para o Fluminense em 1965, mas foi seis anos mais tarde que levou a torcida ao completo delírio ao calar os alvinegros que já cantavam a conquista do título carioca, que lhes cabia com o empate.<br /><br />Raça e técnica fizeram com que Lula deixasse saudades quando se transferiu para o Internacional após ter disputado 375 partidas com a camisa tricolor.");
		createIdol(TCGER, "Manfrini", "http://www.fluminense.com.br/site/futebol/wp-content/uploads/2011/06/manfra.jpg", "A habilidade, o raciocínio veloz, o chute de meia distância tanto com a perna direita quanto com a esquerda e os muitos gols marcados tornaram Antônio Monfrini Neto um dos grandes ídolos tricolores.<br /><br />O sobrenome perdeu a letra O e ganhou um A e o nome Manfrini entrou para o hall dos artilheiro logo no ano de sua chegada ao Fluminense, em 1973. Além de conquistar o título de campeão carioca, o jogador conquistou o coração da torcida.<br /><br />Apontado como sucessor de Samarone, Manfrini foi um meia que se firmou como centroavante e fez uma dupla inesquecível com Rivelino, levantando mais um título estadual em 1975 e outra vez terminando a competição como maior goleador.<br /><br />A passagem de Manfrini pelo Fluminense não foi longa. Em 1975 foi envolvido num troca-troca com o Botafogo, após ter disputado 157 jogos e marcado 61 gols.");
		createIdol(TCGER, "Paulo César Cajú", "http://www.fluminense.com.br/site/futebol/wp-content/uploads/2011/06/pcesar.jpg", "O nome de batismo é Paulo César Lima, mas o menino abusado e de futebol vistoso ficou mesmo conhecido como Paulo César Caju.<br /><br />Dono de um toque de bola refinado, o jogador fazia o que queria pela esquerda dos gramados e já aos 21 anos integrava a seleção brasileira que conquistaria o tricampeonato mundial em 1970.<br /><br />Paulo César chegou ao Fluminense como um grande jogador e integrou a quase imbatível Máquina conquistando o bicampeonato carioca de 75/76. Foi ele, inclusive, que no último minuto da prorrogação contra o Vasco, na decisão do título de 76, cobrou uma falta jogando a bola na área para que Gil escorasse e Doval tocasse de cabeça para decretar a vitória e o título.<br /><br />Com suas roupas vistosas, frases impactantes e postura desafiadora para os costumes vigentes, Paulo César entrou de vez a história do Fluminense ao ser eternizado na música que a torcida cantava a cada jogo: “É covardia, é covardia, com Rivelino, Paulo César e cia…”.");
		createIdol(TCGER, "Paulo Vítor", "http://www.fluminense.com.br/site/futebol/wp-content/uploads/2011/06/pvitor.jpg", "Paulo Vítor Barbosa de Carvalho, começou no Fluminense em janeiro de 1981, sendo comprado ao Vitória-ES.Nasceu em Belém – PA, no dia 7 de junho de 1957, possuindo 1.79 m de altura e 75 Kg. Foi o último grande representante da escola de goleiros do Fluminense. Pessoa de grande caráter e tricolor de corpo e alma até hoje, não saiu dos corações dos torcedores.Sempre atencioso com a torcida, o respeito e carinho tornaram-se recíprocos.<br /><br />Goleiro do Tri-Campeonato 1983/1984/1985 e do Brasileiro de 1984, marcou história no Fluminense pela sua segurança e belas defesas no gol tricolor. Foi ainda campeão do Torneio de Seul ( 1976 ), Paris e Copa Kirin 1987.<br /><br />Em 1985 foi Campeão Carioca levando apenas 12 gols em 24 jogos, o que lhe rendeu a excelente média de 0,5 gol por partida. Toda grande defesa ( Aldo, Vica, Ricardo Gomes, Branco ) depende de um grande goleiro, daí o sucesso deste exemplar jogador e ídolo tricolor.<br /><br />O sucesso em 1984 rendeu-lhe inclusive a merecida convocação para a Seleção Brasileira, junto com outros jogadores tricolores após o Campeonato Brasileiro de 1984.<br /><br />Atuou pelo Flu de 1981 a 1988, tendo participado de 358 jogos e sofrido 278 gols. Ficou sem levar gols em 179 partidas. É o segundo goleiro que mais atuou na história do clube.");
		createIdol(TCGER, "Pintinho", "http://www.fluminense.com.br/site/futebol/wp-content/uploads/2011/06/pintinho.jpg", "Por 8 anos Carlos Alberto Gomes vestiu a camisa tricolor. De 1972 a 1979, Pintinho, como ficou conhecido, desfilou elegância pelo meio-de-campo. Sua classe e o fino trato com a bola o fizeram craque.<br /><br />Antes mesmo de se tornar titular o menino magro e esguio já fazia a torcida vibrar quando o técnico Duque o chamava a cada jogo, já no segundo tempo, para entrar em campo, ao lado de outro jovem tricolor, Kleber. Cada vez mais a técnica de seu futebol se sobressaía e não foi difícil conquistar a vaga de titular.<br /><br />Pintinho integrava uma geração formada nas Laranjeiras e, além de um futebol de encher os olhos, conseguiu empatia grande com a torcida.<br /><br />Conquistou o título carioca em 1973 e repetiu a dose em 75, integrando a Máquina. Na fatídica semifinal do Brasileiro, contra o Corinthians, em 84, quando o Flu perdeu nos pênaltis, foi o autor do gol tricolor no tempo normal de jogo.<br /><br />Em 1979 foi convocado para a Seleção Brasileira para disputar a Copa América. Em 80 se transferiu para o futebol espanhol.");
		createIdol(TCGER, "Rivellino", "http://www.fluminense.com.br/site/futebol/wp-content/uploads/2011/06/rivellino.jpg", "Roberto Rivelino chegou ao Flu já consagrado, afinal era tricampeão mundial, detinha a unanimidade da crítica e a admiração de todas as torcidas. Por isso, era conhecido como o Reizinho do Parque São Jorge, sede do Corinthians, clube pelo qual jogava.<br /><br />O extraordinário jogador, de drible mortal, perna esquerda absolutamente precisa para um passe longo e chute devastador, jogava um futebol de grande beleza, mas com um quê de tristeza, pois o Reizinho se sentina incompreendido pelo seu povo.<br /><br />O Fluminense foi buscá-lo em 1975 e ele chegou ao Rio de Janeiro derrubando o que seria uma verdade absoluta, a de que no Carnaval a cidade só tem olhos para a folia. Ledo engano, Riva estreou a camisa tricolor em um Maracanã lotado por 100 mil torcedores, em pleno sábado de carnaval, com uma atuação exuberante. Marcou 3 gols, sendo um de cabeça, até então inédito em seu vasto repertorio.<br /><br />Os tricolores deixaram de lado a emoção de ver porta-bandeiras e passistas e optaram pelo privilégio de assistir Riva com a camisa do Flu, desfilar seu futebol maravilhoso como sempre, deixando para trás o título de Reizinho para adotar o de Curió das Laranjeiras.<br /><br />Rivelino reinou em um time que passou para a história, foi bicampeão estadual (75/76) e chegou a duas semifinais do Campeonato Brasileiro, jogando embalado pelo canto mavioso de seu inquestionável futebol.");
		createIdol(TCGER, "Ricardo Gomes", "http://www.fluminense.com.br/site/futebol/wp-content/uploads/2011/06/rgomes.jpg", "No futebol brasileiro Ricardo Gomes vestiu uma só camisa: a do Fluminense.<br /><br />Zagueiro de porte, Ricardo Raymundo Gomes foi uma das grandes revelações das divisões de base do clube.<br /><br />No início da década de 80, o carioca começou a escrever sua história na zaga tricolor e pouco depois, em 1983/84/85, conquistou o tricampeonato carioca e o Campeonato Brasileiro de 84.<br /><br />O futebol irretocável de Ricardo e sua atuação na defesa do Fluminense o levaram à seleção brasileira. De 1984 a 1990, Ricardo fez 52 jogos pela seleção, mas uma fatalidade o deixou de fora da equipe que levantou o tetracampeonato para o Brasil. Um estiramento muscular no útlimo amistoso antes da estreia fez com que um dos melhores zagueiros do futebol brasileiro deixasse os gramados sem o título de campeão mundial.<br /><br />Para os tricolores, porém, Ricardo Gomes será sempre um grande campeão.");
		createIdol(TCGER, "Romerito", "http://www.fluminense.com.br/site/futebol/wp-content/uploads/2011/06/romerit2.jpg", "O paraguaio Júlio César Romero Isfran fez história com a camisa 7 do Fluminense.<br /><br />Considerado o maior jogador de seu país, atuava no Cosmos, de Nova Iorque, ao lado de Pelé, quando foi contratado pelo Fluminense, em 1984, por 300 mil dólares.<br /><br />Ao mesmo tempo um jogador técnico, versátil e raçudo, Romerito conquistou os tricolores ao exibir um futebol de gala.<br /><br />Romerito levantou o Campeonato Estadual de 84 e foi o autor do gol que deu ao clube o Campeonato Brasileiro nesse mesmo ano, na primeira das duas partidas contra o Vasco.<br /><br />A torcida o reverenciava e rapidamente o elevou a \"Dom Romero\".<br /><br />Em 85 o Fluminense de Romerito sagrou-se tricampeão estadual.<br /><br />O paraguaio ficou nas Laranjeiras até 88, disputou 215 jogos, tendo marcado 57 gols.<br /><br />E, se os tricolores jamais esqueceram do ídolo, Romerito nunca conseguiu se desligar do clube. Até hoje Dom Romero visita as Laranjeiras e seu coração bate no compasso do hino tricolor.");
		createIdol(TCGER, "Samarone", "http://www.fluminense.com.br/site/futebol/wp-content/uploads/2011/06/samara.jpg", "Ao chegar ao Fluminense em 1965 o jovem santista Wilson Gomes não imaginava o quanto a torcida o reverenciaria nos anos seguintes e, muito menos, que seu amor pelo Fluminense duraria por toda a vida.<br /><br />Senhor do meio-de-campo, Samarone servia os companheiros com perfeição e ainda tinha na força de seu chute uma arma poderosa.<br /><br />O gol que deu o título estadual da segunda divisão à Portuguesa Santista foi sua porta de entrada nas Laranjeiras, aos 19 anos.<br /><br />O craque de cabelos louros e cacheados foi campeão carioca em 1969/71 e campeão da Taça de Prata em 1970.<br /><br />As pernas grossas do jogador conferiam potência aos chutes mas também lhe traziam desconforto ao vestir as meias de algodão amarradas por barbantes, que lhe apertavam e causavam dores na panturrilha. Mesmo usando um modelo especial não era raro ver Santana lhe aplicando massagens à beira do gramado.<br /><br />Samarone ficou no Fluminense até 1971.<br /><br />Hoje, engenheiro civil, segue acompanhando o time e torcendo como verdadeiro tricolor.");
		createIdol(TCGER, "Washington", "http://www.fluminense.com.br/site/futebol/wp-content/uploads/2011/06/washing.jpg", "O baiano Washington César Santos, de 1,88 de altura e grande impulsão formou, ao lado de Assis, uma das mais famosas duplas de ataque dos anos 80.<br /><br />Washington começou no Galícia Esporte Clube, de Salvador, passou por Corinthians e Operário do Mato Grosso do Sul, até que chegou ao Internacional de Porto Alegre. Lá foi bem, mas ganhou destaque quando, junto ao seu fiel parceiro de ataque Assis, se transferiu para o Atlético Paranaense.<br /><br />Em 1983, o já famoso casal 20 (apelido em alusão a um seriado de TV da época) chegou ao Flu e aqui conquistou nada mais nada menos que o tricampeonato carioca 1983/84/85, além do inesquecível título de Campeão Brasileiro de 1984.<br /><br />O apurado faro de gol do atacante proporcionou à torcida tricolor golaços inesquecíveis, como um marcado de bicicleta, contra o Flamengo, no Maracanã.<br /><br />O jogador vestiu a camisa da seleção brasileira em cinco jogos e marcou dois gols.");
		// 1991-2012 //
		createIdol(QTGER, "Darío Conca", "http://www.fluminense.com.br/site/futebol/wp-content/uploads/2011/07/conca-idolos.jpg", "Técnica refinada, habilidade e uma ampla visão de jogo.<br /><br />O meia argentino Darío Conca é sinônimo de profissionalismo e amor ao Fluminense.<br /><br />Durante três temporadas e meia, o jogador disputou 210 jogos e marcou 40 gols com a camisa tricolor. Sua disposição e técnica o transformou em ídolo da torcida.<br /><br />Na histórica campanha da Copa Libertadores de 2008, foi um dos principais jogadores do time. Em 2009, foi um dos pilares do time de Guerreiros. Em 2010, foi o grande nome da conquista do título brasileiro.<br /><br />Com a camisa do Flu, Conca arrebatou vários prêmios: Prêmio Craque do Brasileirão – Craque da Galera: 2009, 2010, Prêmio Craque do Brasileirão – Melhor jogador: 2010, Prêmio Craque do Brasileirão – Melhor meia-esquerda: 2010, Bola de Ouro da Revista Placar: 2010, Bola de Prata da Revista Placar: 2010, Troféu Mesa Redonda – Melhor jogador: 2010 e Troféu Mesa Redonda – Melhor meia-de-ligação: 2010. Tudo isso foi reflexo do desempenho do argentino no Fluminense.<br /><br />Conca estará para sempre no rol dos grandes ídolos do Fluminense.");
		createIdol(QTGER, "Ézio", "http://www.fluminense.com.br/site/futebol/wp-content/uploads/2011/11/ezio1.jpg", "Ézio Leal Moraes Filho, nasceu 15 de maio de 1966 em Ponte de Itabapoana, no Espírito Santo. Revelado pelo Bangu em 1986, chegou ao Fluminense em 1991 onde jogou até 1995.<br /><br />É o nono artilheiro da história do Fluminense com 119 gols em 237 jogos.<br /><br />Não era habilidoso, mas tinha faro de gol.<br /><br />Ézio foi ídolo da torcida tricolor na década de 90 e ficou conhecido como Super Ézio, apelido recebido pelo ex-narrador Januário de Oliveira.<br /><br />Nosso super herói, se destacou marcando gols importantes em sua passagem pelo Fluminense como o gol do título da Taça Guanabara de 1993, fora os 12 gols marcados em Fla x Flu’s sendo o terceiro maior artilheiro tricolor no histórico do confronto.");
		createIdol(QTGER, "Magno Alves", "http://globoesporte.globo.com/Esportes/foto/0,,18238970-EX,00.jpg", "Magno Alves foi projetado nacionalmente em 1998, quando foi contratado pelo Fluminense junto ao Criciúma para a disputa do Torneio Rio-São Paulo e foi uma das gratas surpresas na turbulenta fase em que se encontrava. Junto com Roni, formou um dos ataques mais rápidos do futebol brasileiro. Sua velocidade e explosão eram admiráveis.<br /><br />Pecava na finalização, mas compensava seus erros, com muita vontade e raça.<br /><br />Na Copa João Havelange, quando marcou 20 gols, realizou partidas sensacionais. Na inapelável vitória por 6 a 1 sobre o Santa Cruz, Magno fez cinco gols.<br /><br />Em 2001, novamente artilheiro do time no Campeonato Brasileiro, com 11 gols, sendo decisivo nas partidas finais. Ainda em 2001, chegaria à Seleção Brasileira, disputando a Copa das Confederações.<br /><br />Pelo tricolor carioca, ganhou o Campeonato Brasileiro da Série C em 1999 e o Campeonato Carioca de 2002 tornando-se o décimo maior artilheiro da história do Flu com 111 gols.");
		createIdol(QTGER, "Marcão", "http://www.fluminense.com.br/site/futebol/wp-content/uploads/2011/06/marcao_ajustada.jpg", "Marco Aurélio de Oliveira, popularmente chamado de Marcão, foi eleito como ídolo pela torcida, com 85,9% dos 27.048 mil votos, em enquete realizada nos meses de setembro e outubro de 2010, no Site Oficial do Fluminense. Tímido e de poucas palavras, foge do estereótipo de jogador que tem seu nome gritado nos estádios.<br /><br />Não é artilheiro ou de técnica refinada, mas encantou os tricolores pela sua valentia, raça em campo e amor ao clube.<br /><br />Dentro das quatro linhas, o volante é um marcador incansável, daqueles que parecem se multiplicar no combate ao adversário. Chegou ao Fluminense num dos momentos mais dramáticos da história do clube e logo conquistou a torcida por encarnar o espírito esperado de uma equipe que lutava para sair da Série C do Campeonato Brasileiro. Mesmo aclamado pelos tricolores, não se considerava ídolo. Acreditava que o fato de ter siso reconhecido tarde contribuía para manter os pés no chão, sem se deslumbrar.<br /><br />Além do grande período que jogou no Bangu, também passou pelo Vasco, Criciúma e Bragantino. Alguns clubes até quiseram comprar seu passe (direitos econômicos), mas sempre havia um problema e o negócio não se concretizava. Surgiu então o Fluminense, que lhe deu a grande oportunidade de se firmar. Mas Marcão não reclamava da sorte: \"- Não lamento que as coisas tenham sido assim. Já pensou se eu tivesse sido comprado por outro clube? Hoje não estaria no Fluminense, é a grande oportunidade tenho e não posso ignorá-la\".<br /><br />Sempre que entrava em campo era aclamado com o coro \"Marcão é seleção\". O jogador chegou a ter o seu nome incluído na lista prévia de Emerson Leão para a Copa das Confederações, mas não disputou o torneio e nem teve novas convocações para a Seleção Brasileira.<br /><br />Atuando pelo Fluminense, conquistou os títulos de 1999 – Série C do Brasileiro e os Campeonatos Cariocas de 2002 e 2005. Respeitado por todos, foi o capitão da equipe e o jogador mais antigo do elenco vinculado ao clube. Permaneceu nas Laranjeiras de 1999 a julho de 2005, quando a seu pedido foi liberado para jogar no Al-Arabi do Qatar.<br /><br />Por não se adaptar ao Qatar, retornou ao clube em setembro de 2005 e saiu novamente em dezembro de 2006. Atuou com a camisa tricolor em 397 jogos e marcou 22 gols.");
		createIdol(QTGER, "Renato Gaúcho", "http://www.fluminense.com.br/site/futebol/wp-content/uploads/2011/06/renato8.jpg", "Renato Portaluppi chegou ao clube dividindo a opinião da torcida em relação à validade da sua contratação, afinal era um jogador polêmico e que alguns diziam em fim de carreira.<br /><br />No entanto, em menos de seis meses já era uma unanimidade entre os tricolores pois, com atuações memoráveis e gols inesquecíveis, levou, em 1995, o Fluminense ao título de Campeão Carioca, afastado das Laranjeiras há nove anos. Naquele antológico Fla-Flu, fez um gol de barriga aos 44 minutos do segundo tempo, gravado até hoje na memória de todo tricolor.<br /><br />A figura deste gaúcho com alma de carioca, com os meiões arriados e faixa na testa, levando pânico às defesas adversárias, será sempre motivo de boas lembranças.");
		createIdol(QTGER, "Thiago Silva", "http://www.fluminense.com.br/site/futebol/wp-content/uploads/2011/06/thiago_silva_ajustada.jpg", "Zagueiro que se destaca pela técnica apurada, velocidade, antecipação para uma cobertura perfeita, absoluta noção de colocação, excelente impulsão, além de um forte chute com a perna direita. Com todos esses atributos esse jovem zagueiro, campeão da Copa Brasil de 2007, embora com curta passagem pelo Fluminense, teve com a torcida tricolor uma pronta empatia.<br /><br />Nas partidas, a galera em uníssono gritava seu nome e tinha a resposta na excelência de seu futebol. Muitos torcedores passaram a usar uma munhequeira no pulso esquerdo, sua marca registrada.<br /><br />Thiago teve com o Flu uma identificação tão imediata e espontânea que a camisa tricolor que o vestia parecia envolvê-lo desde sempre, no ventre materno.<br /><br />O \"Monstro\", como era chamado pelos companheiros, entra para o rol dos ídolos tricolores na linha de Pinheiro, Edinho e Ricardo Gomes.");
		
		return idols;
	}
	
	private static void createIdol(int ger, String name, String url, String text){
		idols.put(name, new Idol(ger, name, url, text));
	}

	private void setValues(String name) {
		Idol idol = IdolsActivity.idols.get(name);
		tv_name.setText(idol.getName());
		tv_text.setText(Html.fromHtml(idol.getText()));
		
		if(SplashScreen.isConnected(this) && prefs.getBoolean("cb_imgsdownload", true)){			
			String urlImage = idol.getUrl();
			ll_image.setVisibility(View.GONE);
			new DownloadImageTask(urlImage, iv_image, ll_image).execute();
		}else{
			ll_image.setVisibility(View.GONE);
		}
	}
	
	private class DownloadImageTask extends AsyncTask<Void, Void, Drawable> {
		private String url;
		private ImageView iv;
		private LinearLayout ll;
		
		public DownloadImageTask(String url, ImageView iv_image, LinearLayout ll_image){
			this.url = url;
			this.iv = iv_image;
			this.ll = ll_image;
		}

		@Override
		protected Drawable doInBackground(Void... arg0) {
			try {
				Drawable d = ImageManager.DownloadFromUrl(url, "idol_image");
				return d;
			} catch (IOException e) {
				return null;
			}
		}
		
		@Override
		protected void onPostExecute(Drawable result) {
			if(result != null){
				iv.setImageDrawable(result);
				ll.setVisibility(View.VISIBLE);
			}
			super.onPostExecute(result);
		}
	}
}